# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NN0kYs4riuXCjqeoKd40VZ66Lh1hQIFn
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

# Carrega o dataset
df = pd.read_csv('https://raw.githubusercontent.com/orlandojrps/stream/main/df_final.csv')

# Define as opções do input para seleção da city_area
city_areas = df['city_area'].unique().tolist()
city_area_selected = st.sidebar.selectbox('Selecione a city_area:', city_areas)

# Filtra o dataset com base na city_area selecionada
df_filtered = df[df['city_area'] == city_area_selected]

# Calcula o summary de Price, Beds, Baths e Area
summary = df_filtered[['Price', 'Beds', 'Baths', 'Area']].describe()

# Formata o campo 'Price'
summary['Price'] = summary['Price'].apply(lambda x: "${:,.2f}".format(x))

# Exibe o summary na tela
st.write(summary)